### ISSUE TITLE
Really bad results on Raspberry Pi 4

### ISSUE THREAD

**Issue by lunard** [MozillaItalia/DeepSpeech-Italian-Model#115]
Hello ta all.
I'm using the last version of DeepSpeech (0.9.3) on a Raspberry Pi 4, running Raspberry Pi OS (buster).
I tried to load both the 

- releases/download/2020.08.07/model_tflite_it.tar.xz
- releases/download/2020.08.07/transfer_model_tflite_it.tar.xz

models, but the results are really poor (I'm using the official node example 'nodejs_wav').

Someone has similar experience? Thanks! 

![image](https://user-images.githubusercontent.com/8225134/103147160-b127d480-4752-11eb-9d9d-56b203f82b47.png)

**Comment by Mte90** [comment]
It is something we already discussed on Telegram, right now the quality is very low because we don't have enough dataset to train it.
I invite you to join our telegram groups with @mozitabot to move on the discussion as it is now isn't a bug.
