### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#131]
We need to define the model license and also the script code license.

I think that:

- Model released as CC0, we need to write in the release page of everyone
- Script code license as GPLv3
- Add explanation in the readme and license file

It is now time to discuss so we can close this long waiting task.

**Comment by dag7dev** [comment]
I agree on all the points above described.

**Comment by eziolotta** [comment]
good for me too.

**Comment by Mte90** [comment]
Done :-)
