### ISSUE TITLE
Remove lingualibre

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/DeepSpeech-Italian-Model#19]
In order to simplify development of the italian model I propose to remove the lingualibre dataset.
The reasons are that lingualibre in Italian is only 4 minutes long, so is not so useful to improve the dataset. 
The main issue as pointed out in #17 is that the max test batch size is 16 due to the small lingualibre dataset, but I have not found an easy way to specify it correctly in the docker image (make test_batch_size and batch_size different). Moreover it would force to use a not so optimal test batch for the other dataset.

**Comment by Mte90** [comment]
It is ok for me to remove it but what about #16?

**Comment by mone27** [comment]
I still have to work in it. That dataset seems with more material so probably is worthwhile to work on it

**Comment by mone27** [comment]
fixed in #18
