### ISSUE TITLE
Create archive of wikipedia dump for italian

### ISSUE THREAD

**Issue by massimo1980** [MozillaItalia/DeepSpeech-Italian-Model#20]
actually in build_lm.sh there is:

```curl -sSL https://github.com/Common-Voice/commonvoice-fr/releases/download/lm-0.1/wiki.txt.xz | pixz -d | tr '[:upper:]' '[:lower:]' > wiki_it_lower.txt```

Pointing at french version of wiki
If can be helpfull i have used:
https://raw.githubusercontent.com/alesarrett/CostituzioneItaliana/master/costituzione.txt

**Comment by Mte90** [comment]
I am generating our dump of wikipedia in a txt files so we can replace it

**Comment by Mte90** [comment]
The pack is ready but I have issues on uploading, I will try tonight at home.
