### ISSUE TITLE
Generate an Italian text corpus

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#36]
After discussing in the community (especially @paolo-losi) the model need a better text corpus, right now the available ones have issues with the licensing that we need.
CC0 or public domain, or CC license with commercial support but we want to release just the scripts and not the final dataset to avoid any troubles.
The point is to create a corpus not from wikipedia or encyclopedic, manuals and so on but colloquial resources like chats, discussions/emails, quotes that are more similar to the needs of a voice recognition usage.

So we need to replace https://github.com/MozillaItalia/DeepSpeech-Italian-Model/blob/master/DeepSpeech/it/build_lm.sh#L12 with something else.

So our idea is to generate a static txt file on the fly with a billion words from this kind of text.
We need stuff after 1920+ to get an italian more modern.
For every resource we need to sanitize and cleaning to remove symbols and other stuff not needed.

# Workflow

- [x] Create a new folder `MITADS` = Mozilla Italia DeepSpeech (we can change codename for the corpus, refer to #65)
- [ ] For every source generare an exporter, that sanitize data to remove symbols (<>/ etc)/chapter titles and generate a single txt file
   - [x] Gutenberg
   - [x] Wikiquote
   - [x] Opensubtitle
   - [x] Wikisource
   - [x] Eulogos 
   - [x] An.ANA.S.
   - [x] QALL-ME
   - [x] TED transcription
   - [ ] Wacky
- [x] Tool to aggregate all of them and remove duplicates

# What tools use?

Considering that the deepspeech model is executed on linux machine we can use Bash but is not so very fast so we have to use **Python**.
Also this corpus doesn't need to be generated at every model generation but once for all of them by us.

**Comment by Mte90** [comment]
* https://github.com/c-w/gutenberg, we need to do a list of books and a script to download and sanitize them

**Comment by Mte90** [comment]
On sanitizing we need to remove the titles of the various chapters, basically sentences with few words and a dot.

**Comment by Mte90** [comment]
Gutenberg books that we can use:
```
48361
38338
49626
26169
11305
60657
60092
54178
42198
52484
29955
48206
48727
41157
56943
25265
60586
```

**Comment by Mte90** [comment]
## Wikiquote

Downlaod the last dump like https://dumps.wikimedia.org/itwikiquote/20191101/ and extract the quote (including sanitizing).

**Comment by Mte90** [comment]
## Wikisource

List of some books that fit our needs

* https://it.wikisource.org/wiki/Le_lettere_di_Aldo_Moro_dalla_prigionia_alla_storia
* https://it.wikisource.org/wiki/Nigrizia/Editoriale_giugno_2011
* https://it.wikisource.org/wiki/Il_manifesto_della_guerriglia_Open_Access
* https://it.wikisource.org/wiki/Le_donne_non_vi_vogliono_pi%C3%B9_bene
* https://it.wikisource.org/wiki/A_proposito_di_Leonardo_e_della_sfera_del_fuoco/A_proposito_di_Leonardo_e_della_sfera_del_fuoco
* https://it.wikisource.org/wiki/Lettera_a_Angelo_De_Gubernatis_(17_febbraio_1906)
* https://it.wikisource.org/wiki/Lettera_ai_giudici
* https://it.wikisource.org/wiki/Lettera_ai_lavoratori_americani
* https://it.wikisource.org/wiki/Lettera_ai_cappellani
* https://it.wikisource.org/wiki/Lettera_ai_cappellani

**Comment by Mte90** [comment]
## NUNC
We written to the author to know about the license and if it is downloadable http://www.bmanuel.org/projects/ng-HOME.html

**Comment by Mte90** [comment]
## OpenSubtitles

Seems that this resources are public domain https://www.opensubtitles.org/it

From http://opus.nlpl.eu/download.php?f=OpenSubtitles/v2018/raw/it.zip it is possible to download all the italian subtitles of 2018.

So this scraper need to download that zip (put in cache), extract it, loop every file xml in OpenSubtitles/raw/it/<folder>/<id>.xml.

From this xml file need to extract every sentences and punt in a txt file. This will require a lot of time to process it.

**Comment by Mte90** [comment]
## Dataset Eulogos Chat

A scraper from http://www.intratext.com/IXT/ITA0192/ of the various subpages

## An.ANA.S. 

Download the italiano.zip http://www.parlaritaliano.it/index.php/it/corpora-di-parlato/716-corpus-ananas-multilingue-ananasmt and extract the trascrizioni file that require a lot of sanitization

## Corpus di parlato telegiornalistico. Anni Sessanta vs. 2005

This one is based on doc and pdf files and require sanitization

http://www.parlaritaliano.it/index.php/it/corpora-di-parlato/647-selezione-dal-qcorpus-di-parlato-telegiornalistico-anni-sessanta-vs-2005q

**Comment by Mte90** [comment]
## Wacky

https://wacky.sslmit.unibo.it/doku.php?id=download

**Comment by Mte90** [comment]
## Archive.org

Books that we can download as txt/html and aggregate them (as example):

* https://archive.org/details/tntvillage_217157/mode/2up
* https://archive.org/details/tntvillage_107169
* https://archive.org/details/tntvillage_216065/mode/2up
* https://archive.org/details/tntvillage_217504/page/n3/mode/2up
* https://archive.org/details/tntvillage_222519/mode/2up
* https://archive.org/details/tntvillage_290103/mode/2up
* https://archive.org/details/tntvillage_404218/mode/2up
* https://archive.org/details/tntvillage_464928/mode/2up
* https://archive.org/details/tntvillage_292248/mode/2up
* https://archive.org/details/tntvillage_297587/mode/2up
* https://archive.org/details/tntvillage_289824/mode/2up

**Comment by Mte90** [comment]
Wacky https://wacky.sslmit.unibo.it/doku.php?id=corpora is suitable for us?

**Comment by mone27** [comment]
I personally don't like the MITADS names because it is difficult to pronunce and understand what it meas.
Here i propose some other random ideas:
- MozIta
- MozItaDS
- ItaSpeech (best for me)
- ItaDS

Looking forward to hear your input

**Comment by Mte90** [comment]
MozItaDS for me is fine.

**Comment by Mte90** [comment]
I think that when we do the official release we can change the name to MozItaDS.

**Comment by DanielSWolf** [comment]
@Mte90 I'm currently looking for an Italian text corpus for an open-source project of my own, and your list of sources has been an incredible help to me! I have one question, though: Project Gutenberg lists [about 1000 Italian texts](https://www.gutenberg.org/browse/languages/it), out of which MITADS [appears to use 15](https://github.com/MozillaItalia/DeepSpeech-Italian-Model/blob/master/MITADS/assets/gutenberg_books.txt). How did you choose this subset?

**Comment by Mte90** [comment]
Hi Daniel, the situation for italian is strange  compared to other languages. 
Our evolved in the last 60 years and is different from vocabulary to a lot of things and on gutenberg project is full of text from the 15 century as example.
So in our analysis we chosen to pick italian text from 1930+ to get a modern and similar today.

You can find more information on https://daniele.tech/2019/12/how-the-italian-deepspeech-model-helped-our-mozilla-italia-community/ there is also the recorded version https://video.fosdem.org/2020/UA2.114/how_to_get_fun_with_teamwork.mp4 (but is not complete as the article).

**Comment by DanielSWolf** [comment]
Thank you very much!
