### ISSUE TITLE
Support on text corpus generation for python threads

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#40]
I am wondering if we can speed up the scripts for the text corpus generation using python thread.

It is something that we can do when we will have all the script working, so we can hack all of them to split their process on reading and cleaning data.

Our estimation that is can take like 4 hours now.

**Comment by eziolotta** [comment]
We could use  python package Dask (https://github.com/dask/dask) 
to speeding up text pre-processing.
Dask helps you perform operations on DataFrames, and Lists in parallel.

There would also be FastText, but I don't know if it can help with threads..

**Comment by Mte90** [comment]
I was thinking more to integrate it in every scripts so they can read and parse multiple files at once.

**Comment by Mte90** [comment]
https://github.com/MozillaItalia/DeepSpeech-Italian-Model/pull/53/commits/ac5f4e8ecd9f753f37afc09b6f99f371fa35bea8 should implement parallel processing for opensubtitles so we have an example.
