### ISSUE TITLE
Document Corpus scripts

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#42]
As title we need to explain better the new scripts at https://github.com/MozillaItalia/DeepSpeech-Italian-Model/blob/master/MITADS/README.md

**Comment by mone27** [comment]
Should we write that Readme file in English?

**Comment by Mte90** [comment]
Well on https://github.com/MozillaItalia/DeepSpeech-Italian-Model there is written to write readme in italian.
I think that we have to do it to avoid any confusions and help newcomers.

**Comment by mone27** [comment]
ah I ok I get the point. Maybe also because we are working with Italian specific datasets there is no value in write the readme in english.
