### ISSUE TITLE
Create a tiny sample from the CV dataset

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#48]
* Download the dataset from https://voice.mozilla.org/it/datasets
* Pick some files wav+text
* Compress them and upload on github

**Comment by nefastosaturo** [comment]
[cv-it_tiny.tar.gz](https://github.com/MozillaItalia/DeepSpeech-Italian-Model/files/4610711/cv-it_tiny.tar.gz)
could be a nice one?

**Comment by Mte90** [comment]
Perfect, I will add in the readme!
