### ISSUE TITLE
[output cleaning] ted_importer.py

### ISSUE THREAD

**Issue by nefastosaturo** [MozillaItalia/DeepSpeech-Italian-Model#61]
These are some problems that I've found on looking at ted_importer.py output. I'll write down from the most serious, at least for me :) 

**code issues:**
- clean_log() is not defined
- bs4 lxml parser: bs4.FeatureNotFound. Using BeautifulSoup(data, 'html.parser') it works

**output issues:**

- symbols: ♪ ; ♫ ; T ∇ Sτ ; E=mc² ; 31¼% 

- html escape: (sanitize.py escapehtml() could be useful):

```
&amp; 
&quot;

```
- some unknown chars: eg

```
Nessuno aveva mai studiato l'involucro
L'immagine alle mie spalle mostra
```

- Some sentences starts with 00, seems that new line split numbers: 

```
Ed ecco come userò il mio premio di 10
00 dollari
```

- accents: E' vs È , ò vs o´

```
falo´
È un infuso creato 
```

- when there is an apostrophe the next word occurs without a space. There are lot of these kind: 

```
E'il drone
E'l'applicazione
E'stata
realta'virtuale
E'più
L'immagine che venne un po'dopo aveva una spiegazione semplice
```

- invalid roman numbers: 

```
La natura nel senso del IXX secolo, giusto
VV: Sì, tre persone sono scese sul fondo dell'Oceano Pacifico
```

and about this last one: lot of sentences starts with 2 letter and then ":"  

```
AC: Se dimagrisci un po'
AG: Ci sono certamente implicazioni tecniche
ZF: Scendi tu dal palco

```

**Comment by Mte90** [comment]
@dag7dev do you will take a look on those?

**Comment by Mte90** [comment]
Maybe we can do like in eulogos, just italian alphabet and some symbols

**Comment by nefastosaturo** [comment]
Hey there, need help to detect no-utf8 characters and avoid unknown characters.

A snippet of code to reproduce this problem:

`
import requests

r = requests.get("https://www.ted.com/talks/1468/transcript.json?language=it")
if r.status_code == 200:
    print((r.content).decode('utf-8'))

`

Apart the kinda awkward talk, you'll find unknown chars in the request content. For this specific case there is the \x92 char which is the " ’ " that belongs to windows-1252 encoding .

What I'm trying to do is to do a pre-parse of the raw text and if the decoding fails, I'll just skip it. For this I'm using:

`
            try:
                text.encode('latin1').decode('utf-8')
            except UnicodeDecodeError:
                print("UnicodeError",text)
`

For that specific talks, this try/except works but the except clause triggers even for other chars like "è":

`
s='La funzione di base del grasso corporeo è'
s..encode('latin1').decode('utf8') # triggers UnicodeDecodeError
`


So, given that I got raw bytes from the ted talks, how can I detect not valid utf chars?
