### ISSUE TITLE
deepspeech.Model() fails: AttributeError: 'Model' object has no attribute '_impl'

### ISSUE THREAD

**Issue by Christian-Nja** [MozillaItalia/DeepSpeech-Italian-Model#66]
I tried this code:

https://github.com/MozillaItalia/DeepSpeech-Italian-Model/wiki/Python-Deepspeech-API-utilizzando-file-audio

but it failed, i resolved following this:

https://github.com/mozilla/DeepSpeech/issues/3006

**Comment by Mte90** [comment]
@ilyasmg you need to update the docs

**Comment by ilyasmg** [comment]
Mine works fine with that tutorial's code, and I have DeepSpeech: v0.7.0-alpha.1-0-g60cbe3b
To resolve did you just remove "lm_file" from model.enableDecoderWithLM()? @Christian-Nja

**Comment by Mte90** [comment]
Maybe it's the case to release the tutorial using a stable release and not an alpha.
So we are sure that everything is aligned and works.

**Comment by Christian-Nja** [comment]
No sorry @ilyasmg to resolve i used the code suggested in the answer to that issue: [https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/client.py](url)

**Comment by Mte90** [comment]
I am not sure if the wiki page was updated, @ilyasmg

**Comment by ilyasmg** [comment]
I tried to fix the tutorial and I also tried using the client.py file but I get this error "RuntimeError: CreateModel failed with 'Incompatible model.' (0x2003)" when I use "output_graph.pbmm". I upgraded to deepspeech 0.7.1.
Could it be that the model released 2020.03.13 is not compatible with the stable deepspeech? @Mte90

**Comment by Mte90** [comment]
Probably yes, I will ask to release a new one.

**Comment by Mte90** [comment]
Closing because the latest release use a different DS verison
