### ISSUE TITLE
Supporto per sviluppo

### ISSUE THREAD

**Issue by cooked** [MozillaItalia/DeepSpeech-Italian-Model#67]
Ciao a tutti,
vorrei sapere se c'e'un forum, chat o altro canale ufficiale o non ufficiale dove discutere dello sviluppo di DeepSpeech italiano e dare/avere supporto durante il training o lo sviluppo di un language model custom.

Greazie

**Comment by nefastosaturo** [comment]
Ciao! Ci trovi nel gruppo developers su telegram @MozItaBot https://t.me/mozitabot

**Comment by Mte90** [comment]
Ciao, si lo abbiamo come dice nefastosauro direi che devo aggiornare il readme con queste info, lo faccio subito.
