### ISSUE TITLE
Trie file Generation

### ISSUE THREAD

**Issue by smark-** [MozillaItalia/DeepSpeech-Italian-Model#68]
Hi all,

thanks for the hard-work that you've put in creating this fork. I'm in the process of creating a reduced dictionary to control a robot but I'm having some issues with the trie file generation. I've tried to generate the trie file using the generate_trie script of the 0.7.0a1 native client without success. I've event tried to run it on the lm_binary that comes with the "2020.03.13" release but it still fails to recognize words. This is, for instance, the result if I try to get "cinque sei sette otto nove dieci" recognized:

![example](https://user-images.githubusercontent.com/4362434/83112476-7d0a0980-a0c6-11ea-9edd-9e36e297345b.jpeg)

Obviously everything works fine if I use the lm.binary and trie provided together with the model

**Comment by Mte90** [comment]
The problem is our model that is not recognizing a lot of words (check #36).
If you join us on our telegram @mozitabot in the developers group you can talk with the rest of the community behind this project.
