### ISSUE TITLE
Document docker env variables

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#93]
We want to document the variables in https://github.com/MozillaItalia/DeepSpeech-Italian-Model/blob/master/DeepSpeech/Dockerfile_it.train and also the 4 env files we provide now.

As now there are some variables not very clear, others was just added by us like `only_export` so @lissyx can help us:

- `english_compatible`
- `amp`
- `max_to_keep`
- `n_hidden`
- `lm_beta`
- `lm_alpha`

**Comment by lissyx** [comment]
I'm unsure what is the question here ?

**Comment by Mte90** [comment]
We want to document this parameter but is not clear for us what is their purpose.

**Comment by lissyx** [comment]
> We want to document this parameter but is not clear for us what is their purpose.

They are already documented in CONTRIBUTING.md,have you  checked that ?

**Comment by Mte90** [comment]
You are right -.-'
