### ISSUE TITLE
TTS model

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#97]
https://github.com/mozilla/TTS it is a complete different project but we can release a model also for this.

**Comment by nefastosaturo** [comment]
don't hate me but I'm closing this!

**Comment by nicolalandro** [comment]
Exist some way to contribute to the TTS for italian voice?

**Comment by Mte90** [comment]
The issue is that we never found someone that want to start working on that.
So we need someone that study the mozilla TTS project to see what is needed to start something for italian.

**Comment by nicolalandro** [comment]
Starting from [mozilla/TTS](https://github.com/mozilla/TTS) and clicking in the training guide I arrive to [coqui-ai/TTS](https://github.com/coqui-ai/TTS). I'm in a very entry level situation but I [fork it](https://github.com/nicolalandro/TTS) and I'm triyng to create a config to use with common voice. In particular for now I select the voice of the most frequent speaker to replicate the standard situation to reach a minimum value, but the idea is to train with all common voice, I ask something [there](https://github.com/coqui-ai/TTS/discussions/579).
